SELECT
	CASE WHEN (SELECT LOGICO FROM TSIPAR WHERE CHAVE = 'CONSI_E-R_SPLI') = 'S' THEN AAA.ESTOQUEMENOSRESERVA ELSE AAA.ESTOQUECOMRESERVA END AS ESTOQUE
FROM (
		SELECT
			/*CASE WHEN 
            	NVL(SUM(EST.ESTOQUE),0) > :QTDNEG THEN NVL(SUM(EST.ESTOQUE - EST.RESERVADO),0) + :QTDNEG 
                ELSE NVL(SUM(EST.ESTOQUE - EST.RESERVADO),0) END AS ESTOQUEMENOSRESERVA*/
			NVL(SUM(EST.ESTOQUE),0) AS ESTOQUECOMRESERVA
            , CASE WHEN :CODEMP = :CODEMPPEDIDO THEN NVL(SUM(EST.ESTOQUE - EST.RESERVADO),0) + :QTDNEG  ELSE NVL(SUM(EST.ESTOQUE - EST.RESERVADO),0) END AS ESTOQUEMENOSRESERVA
		FROM TGFEST EST
		WHERE EST.CODLOCAL = 1001
		AND EST.CODEMP = :CODEMP
		AND EST.CODPROD = :CODPROD
) AAA
WHERE
CASE WHEN (SELECT LOGICO FROM TSIPAR WHERE CHAVE = 'CONSI_E-R_SPLI') = 'S'
		THEN AAA.ESTOQUEMENOSRESERVA
		ELSE AAA.ESTOQUECOMRESERVA END > 0