SELECT
--NVL(SUM(EST.ESTOQUE - EST.RESERVADO),0) AS ESTOQUE
NVL(SUM(EST.ESTOQUE),0) AS ESTOQUE
FROM TGFEST EST
WHERE EST.CODLOCAL = 1001
AND EST.CODEMP = :CODEMP
AND EST.CODPROD = :CODPROD
--HAVING NVL(SUM(EST.ESTOQUE - EST.RESERVADO),0) > 0
HAVING NVL(SUM(EST.ESTOQUE),0) > 0